rvm:
  - 1.9.3
  - jruby
  - 2.0.0
  - 2.1.0
  - ruby-head
sudo: false
cache: bundler
env:
  - CHILDPROCESS_POSIX_SPAWN=true CHILDPROCESS_UNSET=should-be-unset
  - CHILDPROCESS_POSIX_SPAWN=false CHILDPROCESS_UNSET=should-be-unset
matrix:
  include:
    - rvm: rbx-3
      env: RBX_RUBY_COMPAT=2.3.1 RBX_VERSION=3.62

  allow_failures:
    - rvm: rbx-3
    - rvm: ruby-head
    - rvm: 2.1.0
      env: "CHILDPROCESS_POSIX_SPAWN=true"
